<?php

require('includes/extn_commerce.cart.inc');
require('includes/extn_commerce.checkout.inc');

const SHIPPING_COURIER = 1;
const SHIPPING_PICKUP = 2;

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter()
 */
function extn_commerce_form_alter(&$form, FormStateInterface $form_state, $form_id): void
{
  // форма Корзины
  if (str_contains($form_id, 'views_form_commerce_cart_form')) {
    extn_commerce_cart_form_alter($form, $form_state);
  }
}




/**
 * Implements hook_ENTITY_TYPE_view().
 */
function extn_commerce_commerce_product_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode)
{
  // здесь добавляется alt для изображений товаров в блоках каруселей
  // (добавление alt раскидано по трём местам)
  // hook_preprocess_field для field_p_images не вызывается для полей или сущностей, выводимых через виджет swiper
  if ($entity->hasField('field_p_images')) {
    $title = $entity->hasField('field_title_ru') ? $entity->get('field_title_ru')->value : $entity->label();
    $volume = $entity->hasField('field_p_volume') ? ' ' . $entity->get('field_p_volume')->entity->label() : '';
    $alt = $title . $volume . ' от JOY PREMIUM';

    if (isset($build["field_p_images"])) {
      foreach(\Drupal\Core\Render\Element::children($build['field_p_images']) as $key => $item) {
        $alt_w_delta = $alt . ($key ? ' [' . $key . ']' : '');
        if (is_numeric($key) && isset($build['field_p_images'][$key]['#item'])) {
          $build['field_p_images'][$key]['#item']->alt = $alt_w_delta;
        }
      }
    }
  }
}
