<?php

require('includes/extn_commerce.cart.inc');
require('includes/extn_commerce.checkout.inc');

const SHIPPING_COURIER = 1;
const SHIPPING_PICKUP = 2;

// аутентификация в CDEK API
// в том числе нужно заменить в service.php
const CDEK_ACCOUNT = 'mkwn6fDly35L0wmtFQbrDLHw9JQ4uweW';
const CDEK_SECRET = '53JkTOSbY8Svrzuf6gFtCydf4dJqtYg5';

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter()
 */
function extn_commerce_form_alter(&$form, FormStateInterface $form_state, $form_id): void
{
  // форма Корзины
  if (str_contains($form_id, 'views_form_commerce_cart_form')) {
    extn_commerce_cart_form_alter($form, $form_state);
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function extn_commerce_commerce_product_variation_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode)
{
  // здесь добавляется alt для изображений товаров в блоках каруселей
  // (добавление alt раскидано по трём местам)
  // hook_preprocess_field для field_p_images не вызывается для полей или сущностей, выводимых через виджет swiper
  if ($entity->hasField('field_pv_images')) {
    $title = trim($entity->label());
    $alt = 'Превью. ' . $title . ' от JOY PREMIUM';

    if (isset($build["field_pv_images"])) {
      foreach(\Drupal\Core\Render\Element::children($build['field_pv_images']) as $key => $item) {
        $alt_w_delta = $alt . ($key ? ' [' . $key . ']' : '');
        if (is_numeric($key) && isset($build['field_pv_images'][$key]['#item'])) {
          $build['field_pv_images'][$key]['#item']->alt = $alt_w_delta;
        }
      }
    }
  }
}
