<?php

require('includes/extn_user.register.inc');
require('includes/extn_user.login.inc');

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\profile\Entity\Profile;
use Drupal\smsru\Auth\ApiIdAuth;
use Drupal\smsru\Client\HttpClient;
use Drupal\smsru\Message\Message;
use Drupal\smsru\SmsRu;
use Drupal\user\Entity\User;

/**
 * Implements hook_form_FORM_ID_alter()
 */
function extn_user_form_profile_user_edit_form_alter(&$form, FormStateInterface $form_state): void
{
  if (!\Drupal::currentUser()->hasPermission('administer site configuration')) {
    $form["field_user_phone"]["widget"][0]["value"]["#disabled"] = TRUE;
  } else {

    // тестирование отправки email
//    \Drupal::service('plugin.manager.mail')->mail('system', 'example_mail_key', 'mega_comp@mail.ru', 'ru', [
//      'context' => [
//        'subject' => 'HTML тестовое письмо',
//        'message' => \Drupal\Core\Render\Markup::create(
//      '<p><strong>Уважаемый(ая) [Имя клиента]!</strong></p>' .
//            '<p>Большое спасибо за ваш заказ в интернет-магазине JOY Premium!  Мы очень рады, что вы выбрали наши продукты.</p>' .
//            '<p><strong>Ваш заказ №[номер заказа] от [дата оформления] успешно оформлен и передан на обработку.</strong></p>'
//        ),
//      ],
//    ], 'bot@joypremium.com');


  }
  $form['actions']['submit']['#ajax']['callback'] = 'extn_user_form_profile_user_edit_form_ajax_update';
}

function extn_user_form_profile_user_edit_form_ajax_update(array &$form, FormStateInterface $form_state)
{
  $response = new AjaxResponse();

  $form['status_messages'] = [
    '#type' => 'status_messages',
    '#weight' => -10,
  ];
  $response->addCommand(new ReplaceCommand('.profile-user-edit-form', $form));

  return $response;
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function extn_user_form_user_pass_alter(&$form, FormStateInterface $form_state): void
{
  $form['actions']["submit"]['#attributes']['class'][] = 'button--primary';
}

/**
 * Загрузить пользователя по указанному логину.
 * Только e-mail и name
 *
 * @return EntityInterface|null
 */
function extn_user_user_load_by_login($login): ?EntityInterface
{
  // Try loading by email.
  if ($user = user_load_by_mail($login)) return $user;

  // Try loading by username.
  if ($user = user_load_by_name($login)) return $user;

  return NULL;
}

/**
 * Загрузить пользователя по номеру телефона в профиле.
 *
 * @return \Drupal\user\UserInterface|false
 *   A fully-loaded $user object upon successful user load or FALSE if user
 *   cannot be loaded.
 */
function extn_user_user_load_by_phone($phone)
{
  // проверить наличие пользователей с таким номером
  $profile_ids = \Drupal::entityQuery('profile')
    ->condition('type', 'user')
    ->condition('field_user_phone', $phone)
    ->accessCheck(FALSE)
    ->execute();

  if ($profile_ids) {
    $profile = Profile::load(reset($profile_ids));
    $uid = $profile->getOwnerId();
    $user = User::load($uid);
  }

  return $user ?? FALSE;
}


/**
 * Отправить СМС код через API SMS.ru.
 * Отправка кода возможна раз в 2 минуты.
 *
 * @param $form_state
 * @return void
 */
function extn_user_sms_send_code($form_state)
{
  $user_phone = $form_state->get('sms_verification_phone');
  $secret = \Drupal::service('func_helper.secret');

  // Проверка на частоту отправки кодов
  $flood = \Drupal::service('func_helper.flood');
  $send_code = $flood->check('sms_verification_send_code', 1, 120, $user_phone);
  $check_code = $flood->check('sms_verification_check_code', USER_FLOOD_ATTEMPTS, USER_FLOOD_COOLDOWN, $user_phone);

  // Если код устарел или удалён из кэша при запросе повторной отправки,
  // генерируем и отправляем сообщение с кодом.
  if ($send_code['allowed'] && $check_code['allowed'] && !$secret->exists($user_phone)) {
    $secret_code = rand(1111, 9999);
    $secret->set($user_phone, $secret_code, 600);
    $sms_text = $secret_code . ' - JOY PREMIUM, код для входа на сайт.';

    // инициализация и отправка смс
    $smsru_auth = new ApiIdAuth('036AD662-0400-7EAE-FF5C-E7B548FFA439');
    $http_client = new HttpClient($smsru_auth);
    $smsru = new SmsRu($http_client);
    $message = new Message($user_phone, $sms_text);
    if (str_ends_with(\Drupal::request()->getHost(), '.local')) $message->setTest(TRUE);
    $response = $smsru->smsSend($message);

    if ($response->getStatusCode() == 100) {
      // Регистрируем отправку кода для контроля перебора.
      $flood->register('sms_verification_send_code', 120, $user_phone);
    }
  }

}

/**
 * Проверить введённый код с отправленным.
 * Код должен быть в элементе "sms_verification_code"
 * Успешная проверка возвращается в "sms_verification_passed"
 *
 * todo Сделать ограничение высылаемых СМС (количество или время),
 *   так как при отправке новой СМС сбрасываются неудачные попытки ввода.
 */
function extn_user_sms_check_code($form_state)
{
  $user_phone = $form_state->get('sms_verification_phone');
  $sms_verification_code = $form_state->getValue('sms_verification_code');
  $flood = \Drupal::service('func_helper.flood');
  $secret = \Drupal::service('func_helper.secret');

  if ($sms_verification_code == 'resend') {
    // удалить secret из кэша
    $secret->delete($user_phone);
    $flood->clear('sms_verification_check_code', $user_phone);
  }
  // Если введён код
  elseif ($sms_verification_code && $secret->isActive($user_phone)) {
    $check_code = $flood->check('sms_verification_check_code', USER_FLOOD_ATTEMPTS, USER_FLOOD_COOLDOWN, $user_phone);

    // проверка на период охлаждения
    if ($check_code['allowed']) {
      // Регистрируем попытку Верификации
      $flood->register('sms_verification_check_code', USER_FLOOD_COOLDOWN, $user_phone);

      // Сверяем введённый код с отправленным.
      $sms_verification_input = $form_state->getValue('sms_verification_code');
      $secret_code = $secret->get($user_phone);
      if ($secret_code && $sms_verification_input == $secret_code) {
        $form_state->set('sms_verification_passed', TRUE);
        $flood->clear('sms_verification_check_code', $user_phone);
        $secret->delete($user_phone);
      }
      else {
        // Удалить значение предыдущего кода, чтобы не подставлялось при обновлении формы.
        $input = $form_state->getUserInput();
        $input['sms_verification_code'] = NULL;
        $form_state->setUserInput($input);
      }
    }
  }
}

/**
 * Вернуть содержимое диалогового окна для ввода кода из СМС
 */
function extn_user_sms_input_dialog($form_state)
{
  $user_phone = $form_state->get('sms_verification_phone');
  $secret = \Drupal::service('func_helper.secret');

  $flood = \Drupal::service('func_helper.flood');
  $check_code = $flood->check('sms_verification_check_code', USER_FLOOD_ATTEMPTS, USER_FLOOD_COOLDOWN, $user_phone);
  $send_code = $flood->check('sms_verification_send_code', 1, 120, $user_phone);

  // попытки закончились, период охлаждения
  $countdown = '';
  $all_disabled = $input_disabled = FALSE;
  if (!$check_code["allowed"]) {
    $notes = '<span class="text-danger">Слишком много попыток ввода кода.<br>Попробуйте через <span class="input-countdown"><span class="counter">' . $check_code['wait'] . '</span> сек.</span></span>';
    $all_disabled = TRUE;
  }
  else {
    // проверка времени жизни сгенерированного кода
    if (!$secret->isActive($user_phone)) {
      $notes = '<span class="text-danger">Время жизни кода истекло. Получите новый.</span>';
      $input_disabled = TRUE;
    }
    // неверный код
    elseif ($check_code['attempts'] < USER_FLOOD_ATTEMPTS) {
      $notes = '<span class="text-danger">Введён неверный код. Осталось попыток: ' . $check_code['attempts'] . '.</span>';
    }
    // всё в норме
    else {
      $notes = 'Введите код, отправленный в СМС.';
    }

    if (!$send_code["allowed"]) {
      $countdown = '<span class="resend-countdown">Получить новый код можно через <span class="counter">' . $send_code["wait"] . '</span> сек.</span>';
    }
  }

  $input_attr = $all_disabled || $input_disabled ? ' disabled' : '';
  $resend_attr = $all_disabled ? ' disabled' : '';

  // доп обёртка div для того, чтобы user-auth-modal можно было найти в behaviour context
  $dialog =
    '<div>' .
      '<div class="user-auth-modal code">' .
        '<div class="form-item form-item--code form-with-verification-dialog-input">' .
          '<input class="code" data-id="1" maxlength="1" type="text"' . $input_attr . ' autofocus />' .
          '<input class="code" data-id="2" maxlength="1" type="text"' . $input_attr . ' />' .
          '<input class="code" data-id="3" maxlength="1" type="text"' . $input_attr . ' />' .
          '<input class="code" data-id="4" maxlength="1" type="text"' . $input_attr . ' />' .
        '</div>' .
        '<div class="form-item">' .
          '<div class="ui-dialog-notes">' .
            '<div class="message">' . $notes . '</div>' .
            ($countdown ? '<div class="countdown">' . $countdown . '</div>' : '') .
          '</div>' .
        '</div>' .
        '<div class="form-actions">' .
          '<button class="form-with-verification-dialog-button resend button button--link button--sm' . ($send_code["allowed"] ? '' : ' hide') . '"' . $resend_attr . '>Получить новый код</button>' .
          '<button class="form-with-verification-dialog-button button button--primary"' . $input_attr . '>Отправить</button>' .
        '</div>' .
      '</div>' .
    '</div>';

  return $dialog;
}

/**
 * Вернуть содержимое диалогового окна для ввода пароля
 */
function extn_user_pass_input_dialog($form_state)
{
  $notes = '<a href="/user/password">Забыли пароль?</a>';

  // доп обёртка div для того, чтобы user-auth-modal можно было найти в behaviour context
  $dialog =
    '<div>' .
      '<div class="user-auth-modal pass">' .
        '<div class="form-item form-item--code form-with-verification-dialog-input">' .
          '<input class="pass" type="text" autofocus />' .
        '</div>' .
        '<div class="form-item">' .
          '<div class="ui-dialog-notes">' .
            '<div class="message">' . $notes . '</div>' .
          '</div>' .
        '</div>' .
        '<div class="form-actions">' .
         '<button class="form-with-verification-dialog-button button button--primary" type="submit">Отправить</button>' .
        '</div>' .
      '</div>' .
    '</div>';

  return $dialog;
}
