<?php

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Markup;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_data_alter().
 */
function extn_views_views_data_alter(array &$data)
{
  if (isset($data['node_field_data'])) {
    $data['node_field_data']['recent_nodes_filter'] = [
      'title' => t('Recent nodes'),
      'help' => t('Filter recent nodes excluding current context.'),
      'filter' => [
        'id' => 'recent_nodes_filter',
      ],
    ];
  }
}

/**
 * Implements hook_views_pre_view().
 */
function extn_views_views_pre_view(ViewExecutable $view, $display_id, array &$args)
{
  // На странице Продукта выводится блок Будет интересно с релевантными по Аромату продуктами.
  // Так как нужного контекста в URL нет, добавляем аргумент (ID аромата из поля field_p_aroma Продукта) вручную.
  // Также исключаем из вывода продукт, на странице которого находимся.
  if ($view->id() === 'karusel_produktov2' && $display_id === 'block_2') {
    if ($variation_id = $_GET['v'] ?? NULL) {
      /** @var \Drupal\commerce_product\Entity\ProductVariationInterface $variation */
      $variation = \Drupal::entityTypeManager()->getStorage('commerce_product_variation')->load($variation_id);

      $commerce_product = \Drupal::routeMatch()->getParameter('commerce_product');
      if ($commerce_product && $commerce_product->hasField('field_p_aroma') && !$commerce_product->get('field_p_aroma')->isEmpty()) {
        $term_id = $commerce_product->get('field_p_aroma')->target_id;
        $args[0] = $term_id;
      }
      if ($view->query) $view->query->addWhere('AND', 'variation_id', $variation_id, '!=');
    }
  }

}

/**
 * Prepares variables for views mini-pager templates.
 */
function extn_views_preprocess_views_mini_pager(&$variables): void
{
  /** @var \Drupal\Core\Pager\PagerManagerInterface $pager_manager */
  $pager_manager = \Drupal::service('pager.manager');

  $element = $variables['element'];
  $pager = $pager_manager->getPager($element);
  if (!$pager) {
    return;
  }
  $variables['items']['total'] = $pager->getTotalPages();
}

function extn_views_views_filters_summary_replacements_alter(&$view)
{
  $request = \Drupal::request();
  $currentPath = $request->getPathInfo();
  $pathArgs = explode('/', trim($currentPath, '/'));

  if ($pathArgs[0] == 'poisk') {
    $keyword = $pathArgs[1] ?? '';
  } elseif ($pathArgs[0] == 'views') {
    $keyword = $_GET["view_args"] ?? '';
  }

  if (!empty($keyword)) {
    $view["custom"] = Markup::create('<span class="item--keyword"><span class="label">по запросу: <span class="value">' . urldecode(Html::escape($keyword)) . '</span></span></span>');
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function extn_views_form_views_exposed_form_alter(&$form, FormStateInterface &$form_state)
{
  // Exposed фильтры в блоках по какой-то причине рендерятся дважды
  // и на втором проходе #action c текущей страницы меняется на taxonomy/term/all.
  // Issue: https://www.drupal.org/project/drupal/issues/3175725
  // Заменить #action на текущий путь, если он имеет значение "/taxonomy/term/all"
  if (isset($form['#action']) && $form['#action'] == '/taxonomy/term/all') {
    $current_path = \Drupal::service('path.current')->getPath();
    $alias_manager = \Drupal::service('path_alias.manager');
    $alias = $alias_manager->getAliasByPath($current_path);
    $form['#action'] = $alias;
  }
}

